### ISSUE TITLE
Password Grant requires secret, incorrect?

### ISSUE THREAD

**Issue by jdelaune** [FriendsOfSymfony/FOSOAuthServerBundle#115]
I'm using the password grant method however it was failing un-nessecarily in my opinion because the token request didn't pass in the client secret. It was my understanding that you shouldn't need to pass in the client secret when using this grant type?

If I comment out lines 685-687 in OAuth2.php then it works as expected (fails on incorrect credentials). However I imagine this will break other grant types.

My suggestion is that line 685 should be changed to:

`if ($this->storage->checkClientCredentials($client, $clientCreds[1]) === FALSE && !self::GRANT_TYPE_USER_CREDENTIALS) {`

But I'm fairly new to OAuth2 so please correct me if I'm wrong.

**Comment by allo86** [comment]
I am new with OAuth2.0 and I would like to know if @jdelaune suggestion is valid:

"I suppose if I lock down that client id to only accept the "password" grant type it's somewhat protected"

Is it a valid workaround? I would like to use this bundle for my app

**Comment by AlmogBaku** [comment]
I agree. The "native use case" is the exact reason "password grant" exists.

**Comment by AlmogBaku** [comment]
also, you can see that the specification REQUIRE not asking for secret in password grant type, see:
http://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified#password

cc: @willdurand

**Comment by AlmogBaku** [comment]
If any of you need an immediate workaround:

1. "Patch" the OAuth class by extending:
```
<?php
/**
 * Created by PhpStorm.
 * User: AlmogBaku
 * Date: 04/12/2015
 * Time: 3:13 PM
 */

namespace Rimoto\ApiBundle\Security;


use OAuth2\OAuth2;
use OAuth2\OAuth2ServerException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class RimotoOAuth2 extends OAuth2
{

    /**
     * Grant or deny a requested access token.
     *
     * This would be called from the "/token" endpoint as defined in the spec.
     * Obviously, you can call your endpoint whatever you want.
     * Draft specifies that the authorization parameters should be retrieved from POST, but you can override to whatever method you like.
     *
     * @param  Request $request (optional) The request
     *
     * @return Response
     * @throws OAuth2ServerException
     *
     * @see      http://tools.ietf.org/html/draft-ietf-oauth-v2-20#section-4
     * @see      http://tools.ietf.org/html/draft-ietf-oauth-v2-21#section-10.6
     * @see      http://tools.ietf.org/html/draft-ietf-oauth-v2-21#section-4.1.3
     *
     * @ingroup  oauth2_section_4
     */
    public function grantAccessToken(Request $request = null)
    {
        $filters = array(
            "grant_type" => array(
                "filter" => FILTER_VALIDATE_REGEXP,
                "options" => array("regexp" => self::GRANT_TYPE_REGEXP),
                "flags" => FILTER_REQUIRE_SCALAR
            ),
            "scope" => array("flags" => FILTER_REQUIRE_SCALAR),
            "code" => array("flags" => FILTER_REQUIRE_SCALAR),
            "redirect_uri" => array("filter" => FILTER_SANITIZE_URL),
            "username" => array("flags" => FILTER_REQUIRE_SCALAR),
            "password" => array("flags" => FILTER_REQUIRE_SCALAR),
            "refresh_token" => array("flags" => FILTER_REQUIRE_SCALAR),
        );

        if ($request === null) {
            $request = Request::createFromGlobals();
        }

        // Input data by default can be either POST or GET
        if ($request->getMethod() === 'POST') {
            $inputData = $request->request->all();
        } else {
            $inputData = $request->query->all();
        }

        // Basic authorization header
        $authHeaders = $this->getAuthorizationHeader($request);

        // Filter input data
        $input = filter_var_array($inputData, $filters);

        // Grant Type must be specified.
        if (!$input["grant_type"]) {
            throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_INVALID_REQUEST, 'Invalid grant_type parameter or parameter missing');
        }

        // Authorize the client
        $clientCredentials = $this->getClientCredentials($inputData, $authHeaders);

        $client = $this->storage->getClient($clientCredentials[0]);

        if (!$client) {
            throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_INVALID_CLIENT, 'The client credentials are invalid');
        }

        if (($this->storage->checkClientCredentials($client, $clientCredentials[1]) === false) && ($input["grant_type"]!=self::GRANT_TYPE_USER_CREDENTIALS)) {
            throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_INVALID_CLIENT, 'The client credentials are invalid');
        }

        if (!$this->storage->checkRestrictedGrantType($client, $input["grant_type"])) {
            throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_UNAUTHORIZED_CLIENT, 'The grant type is unauthorized for this client_id');
        }

        // Do the granting
        switch ($input["grant_type"]) {
            case self::GRANT_TYPE_AUTH_CODE:
                // returns array('data' => data, 'scope' => scope)
                $stored = $this->grantAccessTokenAuthCode($client, $input);
                break;
            case self::GRANT_TYPE_USER_CREDENTIALS:
                // returns: true || array('scope' => scope)
                $stored = $this->grantAccessTokenUserCredentials($client, $input);
                break;
            case self::GRANT_TYPE_CLIENT_CREDENTIALS:
                // returns: true || array('scope' => scope)
                $stored = $this->grantAccessTokenClientCredentials($client, $input, $clientCredentials);
                break;
            case self::GRANT_TYPE_REFRESH_TOKEN:
                // returns array('data' => data, 'scope' => scope)
                $stored = $this->grantAccessTokenRefreshToken($client, $input);
                break;
            default:
                if (filter_var($input["grant_type"], FILTER_VALIDATE_URL)) {
                    // returns: true || array('scope' => scope)
                    $stored = $this->grantAccessTokenExtension($client, $inputData, $authHeaders);
                } else {
                    throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_INVALID_REQUEST, 'Invalid grant_type parameter or parameter missing');
                }
        }

        if (!is_array($stored)) {
            $stored = array();
        }

        // if no scope provided to check against $input['scope'] then application defaults are set
        // if no data is provided than null is set
        $stored += array('scope' => $this->getVariable(self::CONFIG_SUPPORTED_SCOPES, null), 'data' => null,
            'access_token_lifetime' => $this->getVariable(self::CONFIG_ACCESS_LIFETIME),
            'issue_refresh_token' => true, 'refresh_token_lifetime' => $this->getVariable(self::CONFIG_REFRESH_LIFETIME));

        $scope = $stored['scope'];
        if ($input["scope"]) {
            // Check scope, if provided
            if (!isset($stored["scope"]) || !$this->checkScope($input["scope"], $stored["scope"])) {
                throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_INVALID_SCOPE, 'An unsupported scope was requested.');
            }
            $scope = $input["scope"];
        }

        $token = $this->createAccessToken($client, $stored['data'], $scope, $stored['access_token_lifetime'], $stored['issue_refresh_token'], $stored['refresh_token_lifetime']);
        return new Response(json_encode($token), 200, $this->getJsonHeaders());
    }



    /**
     * Returns HTTP headers for JSON.
     *
     * @see     http://tools.ietf.org/html/draft-ietf-oauth-v2-20#section-5.1
     * @see     http://tools.ietf.org/html/draft-ietf-oauth-v2-20#section-5.2
     *
     * @return array
     *
     * @ingroup oauth2_section_5
     */
    protected function getJsonHeaders()
    {
        return array(
            'Content-Type' => 'application/json',
            'Cache-Control' => 'no-store',
            'Pragma' => 'no-cache',
        );
    }
}
```

2. Change the server service class:
```
 parameters:
    fos_oauth_server.server.class: Rimoto\ApiBundle\Security\RimotoOAuth2
```

**Comment by Oxmoze** [comment]
As @alanbem and I said few weeks/months ago, this library only supports confidential clients (password).
The resource owner password credentials grant type will only work this such client. 
If your client is a public one, you cannot use this grant type unless you use a proxy for example. 
Every fixes proposed at the moment create security issues we will not accept (secret = null or disabling credential check). 

We know this library must be updated to support any kind of clients. A project is under development in my repositories. This project already supports public clients.

**Comment by Spomky** [comment]
As @alanbem and I said few weeks/months ago, this library only supports confidential clients (password).
The resource owner password credentials grant type will only work this such client. 
If your client is a public one, you cannot use this grant type unless you use a proxy for example. 
Every fixes proposed at the moment create security issues we will not accept (secret = null or disabling credential check).

We know this library must be updated to support any kind of clients. A project is under development in my repositories. This project already supports public clients.

**Comment by AlmogBaku** [comment]
@Spomky can you please elaborate about the differences between "public client" and "confidential client"? from what I understood from googling its only a term for who is the client.. How is that different from the server perspective?

About other bundle- this bundle(or only its server) looks pretty good, and it's supports JWT(which reduce dramatically the server overhead):
https://github.com/bshaffer/oauth2-server-bundle

**Comment by Spomky** [comment]
I already explained the main differences between public and confidential client on this page (see [this answer](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/115#issuecomment-59072645 or [this one](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/115#issuecomment-67612553)).

I cannot compare this library with other ones because I do not use them and it really depends on your needs. If you think `bshaffer/oauth2-server-bundle` can help your project to go forward, try it.
The project I was talking about in my previous message supports JWT too (grant type and client authentication) including encrypted JWT, but this project is not yet ready for production (see [the latest news here](https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/47#issuecomment-140736862)). If you want for this issue (and a lot of other issues) to be closed, then you are kindly invited to test this project send us feedback. I appreciate any kind of support.

**Comment by AlmogBaku** [comment]
@Spomky your project looking really good!
The only one thing I hated is this "plugin" thing. Why?
The convention is symfony for extending an 3rd party is either override a parameter which contains the service class name, or overriding it int config

**Comment by Spomky** [comment]
We should talk about this topic directly on the project page. Open an issue if you want.
To explain briefly, the plugins allow you to activate the components you need.
Nothing prevent you from extending the bundle or its component and override services.

**Comment by jayesbe** [comment]
The password grant type is not implemented the way it should be. I know I am a nobody.. but its clearly obvious that it is not. Every use case defined anywhere says for Native Mobile applications, where you DO NOT want the client secret exposed.. should use the PASSWORD grant type.  There are umpteenth web articles that say this should be so. 

Here is one from last year https://stormpath.com/blog/the-ultimate-guide-to-mobile-api-security/

I am building a ReactNative app that needs to fetch an access_token from the symfony2 server. According to every piece of documentation I can find.. I need to send grant_type=password&client_id=XXX&username=YYY&password=ZZZ

why are you asking for client_secret when it should NOT be exposed ?

**Comment by johnpancoast** [comment]
From [https://tools.ietf.org/html/rfc6749#section-10](https://tools.ietf.org/html/rfc6749#section-10).
> When client authentication is not possible, the authorization server
   SHOULD employ other means to validate the client's identity

... and ...

> The authorization server SHOULD NOT process repeated authorization
requests automatically (without active resource owner interaction)
without authenticating the client or relying on other measures to
ensure that the repeated request comes from the original client and
not an impersonator.

This one's important when you think about refresh tokens. If an attacker got a hold of an access and refresh token (not unimaginable) and you aren't requiring *any* client authentication (since anyone can pass an ID) then the client can be impersonated and you've lost.

Also you cannot validate a client's identity by passing just a client id because [https://tools.ietf.org/html/rfc6749#section-2.2](https://tools.ietf.org/html/rfc6749#section-2.2)

> The client identifier is not a secret; it is exposed to the resource owner and MUST NOT be used
alone for client authentication.

However, the spec seems to have purposefully been left open on a lot of things and just makes suggestions in a lot of cases but anyone suggesting to not require the client secret has likely not considered that the spec suggests otherwise. There are still ways you could authenticate your apps/clients without shipping the secret in public code (with your own tokens or something).

Anyway, if you don't care about authenticating clients it's still pretty easy to use this lib and bypass the need for the secret. **I just wouldn't do this..**

```php
    // install this lib as normal then just add your own method to proxy to the oauth endpoint.
    public function authenticateAction(Request $request)
    {
        $clientSecret = /* do a lookup by client id to find secret */;

        // send and return response from oauth token request
        return $this->get('kernel')->handle(
            Request::create(
                $this->get('router')->generate('fos_oauth_server_token'),
                'POST',
                [
                    'client_id' => $request->get('client_id'),
                    'client_secret' => $clientSecret,
                    'username' => $request->get('username'),
                    'password' => $request->get('password'),
                    'grant_type' => 'password'
                ]
            ),
            HttpKernelInterface::SUB_REQUEST
        );
    }
```

**Comment by desmax** [comment]
Struggling for 1.5 days already to implement secure OAuth for my javascript\ php api application.
Everywhere is only fuzzy recommendations how to do it. any ready for prod alternatives for this library? 
Currently I used solution by @johnpancoast, but Im not sure if its secure enough.
I limited client to password and refresh_token grant types + plus my front application is behind SSL.
anyone can help?

**Comment by johnpancoast** [comment]
@desmax, I've always been confused it too! Some people suggest that mobile apps don't need to pass the secret but the spec seems to say not to do that. It doesn't give much more info than that unless I'm missing something... I'm sure someone else has more info than me. Been thinking that it might be because it's for authorization rather than authentication and it kind of leaves anything authentication related up to the implementer... maybe?

Anyway, have you looked at one of the other grant types?

**Comment by johnpancoast** [comment]
@desmax, did you look into the [other flows in OAuth](https://tools.ietf.org/html/rfc6749#section-4)?

**Comment by desmax** [comment]
@johnpancoast yes, looks like I should go with Implicit Grant, with auth via form and then redirect back to front url with access token. But this obviously brings some additional work and login page should be coded in API repo, apart from main web application.
Plus its not clear - what to do after access_token expires, since I don't have access to refresh token?
Should I pass it via url fragment as well?

**Comment by jdelaune** [comment]
I wouldn't use refresh tokens with implicit. Keep the user "logged in" on the auth project via a cookie. Then when your access token expires send them back to auth and you come straight back to your application since they are already logged in with a new access token.

**Comment by Spomky** [comment]
The main issue I see here is that you are trying to use the OAuth2 Framework protocol to authenticate users. But this is not the purpose of the protocol.
OAuth2 only allows a client to access on user resources i.e. it is a delegation protocol.

If you want to authenticate users using OAuth2, then you have to use the OpenID Connect extension that issues ID Tokens. OIDC provides an easy way to check if the user is still logged in or not using the ID Token.
Unfortunately, this extension is not supported by the bundle nor the library.

**Comment by desmax** [comment]
>Then when your access token expires send them back to auth
Thank you. I will use that.
Regarding OpenID: This is getting more and more complicated. I amazed that there is still not bullet proofed solution for such a common setup - php api + js web app. 
Im not sure that I want "to authenticate users using OAuth2" - my main problem is that I want to secure my api and I though OAuth is the way to go.

**Comment by Spomky** [comment]
>I amazed that there is still not bullet proofed solution for such a common setup - php api + js web app.

This is my issue #0 and why I created [this organization](https://github.com/OAuth2-Framework)

**Comment by desmax** [comment]
@Spomky can that already be used in prod for my use case?

**Comment by johnpancoast** [comment]
@Spomky yeah, I forgot to mention authorization vs. authentication. OAuth is definitely about authorization but it includes authentication in parts of the spec (or at least vaguely and then leaves authentication to you) and using oauth in combination with other things, like this lib and fos user can work well to do authentication and authorization for a lot of cases while still sticking to the spec, right? I think the issue is both some misunderstanding of oauth and authorization vs. authentication but also just that people want to be able to transfer the ease of those other cases into mobile apps, which are just public clients and oauth seems to leave those cases mostly up to implementer. Your repos look to fill some gaps for sure though!

**Comment by wadjeroudi** [comment]
@Spomky even if a new bundle may be the right solution. You forget that a lot of symfony applications / frameworks depend on this FOSOAuthServerBundle. You should at least add a config parameter that needs to be set explicitly to allow no client_secret for grant type password.

**Comment by desmax** [comment]
I discovered this bundle as an alternative 
https://github.com/lexik/LexikJWTAuthenticationBundle

**Comment by Spomky** [comment]
The purpose of the bundles are different. 
This one helps you to delegate access on resources throughout the OAuth2 framework protocol and the one you mentioned provides an user authentication layer based on Json Web Tokens.

**Comment by gabykant** [comment]
I'm still asking myself why can't I just ignore the **grant_type, client_id and client_secret** ?
Because we already have **username** and **password** as auth parameters.
Can someone explains this to me please ?

**Comment by Spomky** [comment]
The key parameter `grant_type` is required by the specification. With the Password grant type, its value must be `paswword`.
`client_id` and `client_secret` are for the client authentication. Not mandatory if the client is authenticated through the basic authentication scheme for example.
The `username` and `password` are used to identify the resource owner and are therefore mandatory.

**Comment by wadjeroudi** [comment]
@Spomky what is the status about your new library https://github.com/OAuth2-Framework/server-library
Is there any roadmap for the replacement of fosoauthserver ?

**Comment by Spomky** [comment]
Hi @wadjeroudi,

I propose for everybody that is interested in this library to discuss on [the dedicated Gitter room](https://gitter.im/OAuth2-Framework/Lobby).

[There was a discussion about an hypothetical replacement of this bundle](https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/47#issuecomment-59279493), but there is not roadmap for that and, for many reasons, I am not sure this is a good idea.

**Comment by wadjeroudi** [comment]
Ok thx.
What is your advice if you need an oauth server for a webapp using grant type password ?
Switch to an other bundle ?
