### ISSUE TITLE
ObjectId's or no ObjectId's?

### ISSUE THREAD

**Issue by wcummings** [FriendsOfSymfony/FOSOAuthServerBundle#186]
I'm trying to setup the bundle with doctrine+mongodb, and I'm able to create oauthclients just fine, however the token endpoint tries to look up clients with a string field for _id (i.e. "blahblah" instead of ObjectId("blahblah")).

If I insert a new client document with the id as a string, the token endpoint works as expected and I get a bearer token. Is this a bug, or have I misconfigured something?

**Comment by jhogendorn** [comment]
I too have run into this issue, did you find an appropriate fix?

**Comment by wcummings** [comment]
I did, but I can't remember.

@mullanaphy you remember by any chance?

**Comment by jhogendorn** [comment]
I solved this by specifying the type of the field as 'object_id', which seems to fix all the translation between type issues.
