### ISSUE TITLE
Authorize and get access token manually in the API, so without redirectIUrl...

### ISSUE THREAD

**Issue by manonthemoon42** [FriendsOfSymfony/FOSOAuthServerBundle#219]
I'm trying to use FOSOAuthServerBundle. It works pretty well but I try to make it works in API... When I register a new user I create a new client and I would like to give him authorization directly. The request of the access_token will be done when the user will log in...

The problem, the example given in the documentation, it makes a redirection to an authorization page, and after it will redirect to an URL... It would be great to it without any redirection, only to make the authorization...To do it manually... I plan to get the access_token manually too... Hopefully it's possible. 

Part of my register code :

```
$user->setUsername($name);
$user->setEmail($email);
$encoder = $this->get('security.encoder_factory')->getEncoder($user);
$password_user = $encoder->encodePassword($password, $user->getSalt());
$user->setPassword($password_user);

$clientManager = $this->get('fos_oauth_server.client_manager.default');
$client = $clientManager->createClient();
$client->setRedirectUris(array('http://localhost:8888/app_dev.php'));
$client->setAllowedGrantTypes(array('token', 'authorization_code'));
$clientManager->updateClient($client);

$user->setClient($client);

// Here we would like to authorize the user witout redirection :
return $this->redirect($this->generateUrl('fos_oauth_server_authorize', array(
            'client_id'     => $client->getPublicId(),
            'redirect_uri'  => 'http://localhost:8888/app_dev.php',
            'response_type' => 'code'
        )));
```

I would like to authorize without any redirection... Because it's in API :/ , so no URL... Is there another way to authorize ?

Thanks

**Comment by papoola** [comment]
This is a good way to implement oauth2 without using autorization:
http://blog.tankist.de/blog/2013/08/20/oauth2-explained-part-4-implementing-custom-grant-type-symfony2-fosoauthserverbundle/

**Comment by vooxo** [comment]
I was also looking for this and found the way on http://matkodjipalo.com/index.php/2016/08/10/symfony-rest-api-user-login/
