### ISSUE TITLE
Handling API roles/scopes for a webapp

### ISSUE THREAD

**Issue by Ninir** [FriendsOfSymfony/FOSOAuthServerBundle#231]
Hi everyone.

I have a question related to scopes with OAuth, and perhaps with the bundle.

To illustrate this, let's take the example of a webapp/administration consuming a RESTful web API using OAuth as security management solution.
- The server is configured to support a given list of scopes (scopes: administration edition) and roles (ROLE_ADMINISTRATION, ROLE_EDITION etc). The bundle translates scopes to roles for better handling, this is known.
- Regarding the administration webapp, there are multiple level of administration. For instance: administrator, editor, other. This means the webapp displays menus or not based on the scopes/roles of the user.

Now, it is possible, from the API, to set roles for a given users when editing the profile. So a user could have ROLE_ADMINISTRATION for instance.
Then, when authenticating, meaning when getting an access_token, I would like to know how you guys would handle this case (i.e getting the user's permissions at this point please)?

I tried setting scopes for a request, but the returned token has the same tokens that what I passed. Can't really see how to do that.

Any other resources/documents/use case would be really appreciated.

Thanks for your time and help.

**Comment by DIOHz0r** [comment]
Hello, I'm wondering something like this but in a diferent way, let me explain it, I got a public APP and a API with this cases..

The app is authorized by grant_type client_credentials, so the API will return scope "public" on /v2/token result acction.

If a user loggin in the app, the API will return the scope with a upper level access, something like scope: "user" (based on getRole() method).

When or how can this be done and changed?. I don't if if this is valid or is wrong.
