### ISSUE TITLE
Remove token from server

### ISSUE THREAD

**Issue by cortesmartina** [FriendsOfSymfony/FOSOAuthServerBundle#236]
Hi everyone,
Found the question on stackoverflow by someone else, but it remains unanswered. I wonder the same (<a href="http://stackoverflow.com/questions/22112915/how-to-fosoauthserverbundle-logout-or-better-revoke-token">View on stackoverflow</a>).
Basically, I cant achieve to logout the user on the server.
Will appreciate any help, the whole bundle is working wonderfully.

**Comment by hpatoio** [comment]
You can use the command `app/console fos:oauth-server:clean` to do it.
See: https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Command/CleanCommand.php
