### ISSUE TITLE
Return JSONP instead of JSON

### ISSUE THREAD

**Issue by mbates** [FriendsOfSymfony/FOSOAuthServerBundle#252]
I am using this bundle with FOSUserBundle & FOSRestBundle

I've got everything setup successfully, but I can't figure out how to return the AccessToken in jsonp instead of json.

In my app, if I send a "json request" it gets rejected with
The 'Access-Control-Allow-Origin' header contains the invalid value 'null'
as expected, as the app is on a separate domain.

If I send a jsonp request I get json back, which is rejected by the app.

I can "fake" the response by editing oauth2-php/lib/OAuth2/Model/OAuth2.php => function grantAccessToken()

I changed the line
return new Response(json_encode($token), 200, $this->getJsonHeaders());
to 
return new Response('callback('.json_encode($token).')', 200, $this->getJsonHeaders());

but that approach is obviously not going to go very far. It was just an attempt to find out where I can alter the response.

I looked at creating my own grant extension, but it looks like those just return $user data, I can't see a way to get them to affect the response format.

Is there a config setting I am unaware of?

Thanks,
Mike

**Comment by marvoh** [comment]
Thank you for this!
