### ISSUE TITLE
Grant type questions

### ISSUE THREAD

**Issue by ruscon** [FriendsOfSymfony/FOSOAuthServerBundle#295]
Hi, I'm in doubt about grant_types.
Grant type "User Credentials" require user's id & secret.
Grant type "Refresh token" in addition to user's id & secret require the refresh_token.
Questions:
1. I can't understand, whats the advantages of "refresh token" grant type in comparison to "User credentials" (both require client id & secret, and refresh token is used only with previous params ). May be some additional capabilities. In general - when should I use "refresh token" grant type?
2. As I understood this library uses http basic like authentication method of client. Are there any  http authentication methods implemented.

**Comment by Spomky** [comment]
The Resource Owner Grant Type requires an user ID and password. It is used to **get an access token** and a refresh token.
The Refresh Token Grant Type only requires the refresh_token parameter. It is used to **renew an access token** and get a new refresh token.

The HTTP Basic Authentication is used to authenticate your client and is described by the RFC6749. If you can not use it, you can authenticate your client using `client_id` and `client_secret` in the body request.

**Comment by ruscon** [comment]
> The Refresh Token Grant Type only requires the refresh_token parameter. It is used to renew an access token and get a new refresh token.

It is not true, i was check it.
The Refresh Token Grant Type in this moment requires: grant_type, refresh_token, client_id and client_secret.
Example:
```
PROVIDER_HOST/oauth/v2/token?client_id=CLIENT_ID&client_secret=CLIENT_SECRET&grant_type=refresh_token&refresh_token=REFRESH_TOKEN
```

**Comment by Spomky** [comment]
I said that regarding the sentence you wrote : Grant type "Refresh token" in addition to user's id & secret require the refresh_token.

I know that, for every request, you have to specify the grant type you want to use and that your client has to be authenticated.

**Comment by ruscon** [comment]
Ok, i got it, thx

**Comment by AlexMakII** [comment]
Hi. Just to know.
If I'd like to authenticate an app without client_secret - I'll have to implement such authenticate logic by myself, because on this moment only HTTP basic is supported.
PS. About Client Credentials - its used only to identify the app itself, and cant be enoiugh to authenticate the app's user?

**Comment by Spomky** [comment]
For public clients, see #266
