### ISSUE TITLE
Cannot install bundle

### ISSUE THREAD

**Issue by marvoh** [FriendsOfSymfony/FOSOAuthServerBundle#301]
It's two days now of wracking my head and trying everything on google but cannot get this bundle to install despite having used it in previous applications.

Each time I try to install any version of it, I get the error, " - The requested package friendsofsymfony/oauth-server-bundle could not be found in any version, there may be a typo in the package name."

Can someone please help?

**Comment by renatomefidf** [comment]
Did you fix it? You can use dev-master or an specific commit with composer
