### ISSUE TITLE
No route found for GET /oauth/v2/auth_login

### ISSUE THREAD

**Issue by adadgio** [FriendsOfSymfony/FOSOAuthServerBundle#324]
Everything is configured according the the documentation. Lots of people have this problem. I don't really know where to look, this is frustrating !

**Comment by Spomky** [comment]
The reason is that this route is not part of this bundle.
See https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/tree/master/Resources/config/routing

**Comment by adadgio** [comment]
Thats what i thought ! I don't think its clear in the docs though... so we have to create our own auth login form with FOSOAuthServerBundle right ?

**Comment by Spomky** [comment]
Yes, the authentication on your application remain the same as usual (e.g. using FOSUserBundle).
You also have to protect the route `/oauth/v2/auth` behind a firewall.

**Comment by sohildesaihs** [comment]
Hello,

I am using symfony 4.1 and this solution doesn't seem to work for me. I am always getting 404 Route not found error for /oauth/v2/auth_login path

can someone please help for symfony4.1?

Thank you
