### ISSUE TITLE
FOSUserBundle's EmailUserProvider is not used anymore when password_grant is used

### ISSUE THREAD

**Issue by aderuwe** [FriendsOfSymfony/FOSOAuthServerBundle#334]
Possibly this relates to #320?

In any case, email login does not work through OAuth's password_grant. It does work when simply logging in to the backend (through the normal mechanism, I mean).

**Comment by wodka** [comment]
have you set the configuration to do so?

```
fos_oauth_server:
    service:
        user_provider: fos_user.user_provider.username_email
```

**Comment by aderuwe** [comment]
Oh no, how could I miss it... Thanks!
