### ISSUE TITLE
How to override exception messages?

### ISSUE THREAD

**Issue by edamov** [FriendsOfSymfony/FOSOAuthServerBundle#337]
I want to override exception messages to my own. What is the best way to do it?
For example, I'am going to override messages from this method:
```
// friendsofsymfony/oauth2-php/lib/OAuth2.php

    /**
     * @param IOAuth2Client $client
     * @param array         $input
     *
     * @return array|bool
     * @throws OAuth2ServerException
     */
    protected function grantAccessTokenUserCredentials(IOAuth2Client $client, array $input)
    {
        if (!($this->storage instanceof IOAuth2GrantUser)) {
            throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_UNSUPPORTED_GRANT_TYPE);
        }

        if (!$input["username"] || !$input["password"]) {
            throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_INVALID_REQUEST, 'Missing parameters. "username" and "password" required');
        }

        $stored = $this->storage->checkUserCredentials($client, $input["username"], $input["password"]);

        if ($stored === false) {
            throw new OAuth2ServerException(self::HTTP_BAD_REQUEST, self::ERROR_INVALID_GRANT, "Invalid username and password combination");
        }

        return $stored;
    }
```

**Comment by nnmer** [comment]
+1
I have similar question. I want to add a "code" variable to the response with specific number, other just "invalid_grant" which is ambiguous

**Comment by nnmer** [comment]
the only way i see now is to overwrite the OAuthListener constructor. Take all nested constructors and put it to my into one parent constructor and change data there then. But hope there is some better solution to overwrite oAuth2ServerException itself

**Comment by renatomefidf** [comment]
Exception handler is probably what you guys want
http://symfony.com/doc/current/bundles/FOSRestBundle/4-exception-controller-support.html

**Comment by Mohammadtrabelsi** [comment]
Any solution to this problem please ?

**Comment by edamov** [comment]
@Mohammadtrabelsi I resolved it with extending OAuth2/OAuth2 class and overriding methods.
You can override the default package class OAuth2 in services.yml:
```yaml
parameters:
    fos_oauth_server.server.class: My\Bundle\OAuth2\OAuth2
```

**Comment by Mohammadtrabelsi** [comment]
thanks for your responce 
after adding those 2 line in service.yml and creating the OAuth2 class in the same adress in my bundle ,I got this error :
```
FatalErrorException in OAuth2.php line 50:
Error: Cannot redeclare class OAuth2\OAuth2
```
