### ISSUE TITLE
My users come from another source

### ISSUE THREAD

**Issue by Glideh** [FriendsOfSymfony/FOSOAuthServerBundle#338]
I'm building an OAuth server which authentifies users coming from another source (actually another server).

I have created a custom `UserProvider` which works fine with the default Symfony security layer. I have my implementation of UserInterface but it's obviously not an Entity of the database.

Implementing the classes for [`AccessToken`](/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Model/AccessToken.php), [`RefreshToken`](/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Model/RefreshToken.php) & [`AuthCode`](/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Model/AuthCode.php) I defined the user reference as

```php
//...
/**
 * @ORM\Column(type="integer")
 */
protected $user_id;
//...
```

Does it seem logical until there ?
Now the true question is:
How can I link my users to the different tokens ?

**Comment by merk** [comment]
I have something similar.

We use a postLoad listener to populate the user properties. We implemented the OAuthServerBundle entities storing a username instead of the user relationship.

The listener looks something like:

```php
    # ...

    public function postLoad(LifecycleEventArgs $event)
    {
        $object = $event->getObject();

        if (
            $object instanceof AccessToken or
            $object instanceof AuthCode or
            $object instanceof RefreshToken
        ) {
            $user = $this->userProvider->loadUserByUsername($object->getUsername());
            $object->setUser($user);
        }
    }
```

And the AccessToken entity looks something like

```php
class AccessToken extends BaseAccessToken
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var int
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Infinite\SSO\Entity\OAuth\Client")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $client;

    /**
     * @ORM\Column(type="string")
     * @var string
     */
    protected $username;

    public function setUser(UserInterface $user)
    {
        if (!$user instanceof User) {
            throw new \InvalidArgumentException("User must be an instance of InvocationBundle User");
        }

        $this->username = $user->getUsername();
        $this->user = $user;
    }

    public function getUser()
    {
        if (!$this->user) {
            throw new \RuntimeException("Unable to get user - user was not loaded postLoad");
        }

        return $this->user;
    }

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }
}

**Comment by merk** [comment]
The other objects that map to users from FOSOAuthServerBundle need to be mapped in a similar way to the AccessToken.

**Comment by Glideh** [comment]
Thank you very much for this tip, it seems a good idea.
I'm not familiar with the `LifecycleEvent`s though, should the `postLoad` callback be defined in my `User` class ?

**Comment by merk** [comment]
Its a doctrine event, postLoad cant be on your entity in this case because it has an external dependency. You'll need to define a service that is tagged as a doctrine event listener

**Comment by Glideh** [comment]
Ok I'll try that, thx

**Comment by Glideh** [comment]
Seems fine, I also used a trait.
I [answered the solution in Stackoverflow](http://stackoverflow.com/questions/31583852#31590872)
Thanks again
