### ISSUE TITLE
Got this error when user is redirected to oauth/v2 page

### ISSUE THREAD

**Issue by tuongaz** [FriendsOfSymfony/FOSOAuthServerBundle#343]
`Error: Call to a member function getUser() on a non-object line 41`

FOS/OAuthServerBundle/Controller/AuthorizeController.php at line 41:
`$user = $this->container->get('security.context')->getToken()->getUser();`

The `$this->container->get('security.context')` returns null

**Comment by mappedinn** [comment]
So, how did you fixed the problem?

I have the same problem!
