### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by chriwup** [FriendsOfSymfony/FOSOAuthServerBundle#345]
Do you plan on creating a new release soon? Symfony2.7 now being the new LTS, for people relying on stable dependencies like me it would be nice to get rid of depreciation warnings that have been fixed in the master branch.

Thanks.

**Comment by garak** [comment]
:+1:

**Comment by renatomefidf** [comment]
:+1:

**Comment by Garfield-fr** [comment]
:+1:

**Comment by Ener-Getick** [comment]
#374 has been merged and I'll create ``1.5.0-BETA1`` soon.
Feedbacks are welcome :smiley:

**Comment by merk** [comment]
My integration tests pass with the latest dev-master commit.

**Comment by MarijnKoesen** [comment]
Our integration and acceptance tests are green as well on dev-master (with symfony 2.7.8)

**Comment by Ener-Getick** [comment]
I just released a beta version https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/releases/tag/1.5.0-BETA, I'll wait a few days to see if there are reports and otherwise I'll publish a new stable release 😉

**Comment by Ener-Getick** [comment]
See https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/releases/tag/1.5.0 :smile: 

Thanks everyone !
