### ISSUE TITLE
CORS Authorization

### ISSUE THREAD

**Issue by ihorml** [FriendsOfSymfony/FOSOAuthServerBundle#346]
I cannot to make POST (application/json) request to take a token. I take the next error:
`XMLHttpRequest cannot load https://example.com/oauth/v2/token. The 'Access-Control-Allow-Origin' header contains the invalid value 'null'. Origin 'http://localhost:3000' is therefore not allowed access.`

The problem is you denied access for `OPTIONS` method for this url. But I need this method allowed because a browser will send a "OPTIONS" method to the server. This is a "sniff" by the browser to see if the server is cool with you POSTing to it. The server responds with an "Access-Control-Allow-Origin" telling the browser its OK to POST|GET|ORIGIN if request originated from "http://from.com" or "https://from.com". Since the server is OK with it, the browser will make a 2nd request (this time a POST). 

How can I fix that?

**Comment by Spomky** [comment]
You can easily fix this using your own route.
Do not add the one provided by the bundle ; just add:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/routing http://symfony.com/schema/routing/routing-1.0.xsd">
    <route id="fos_oauth_server_token" path="/oauth/v2/token" methods="GET POST OPTIONS">
        <default key="_controller">fos_oauth_server.controller.token:tokenAction</default>
    </route>
</routes>
```

**Comment by dVaffection** [comment]
Please notice that you can also override just `methods` key, e.g.
```yaml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    methods:  [GET, POST, OPTIONS]
```
