### ISSUE TITLE
Per client permission

### ISSUE THREAD

**Issue by hpatoio** [FriendsOfSymfony/FOSOAuthServerBundle#348]
Is there a built in system to allow per client permission to every access point ? 
I want `client A` be able to access all my endpoints and `client B` only some of them despite the user.

**Comment by renatomefidf** [comment]
You probably can achieve that by using Roles, just follow the symfony2 docs

**Comment by stof** [comment]
This looks like what scopes are for.

**Comment by hpatoio** [comment]
@stof yes. You are right. As usual. 

@renatomefidf you don't event need a voter (for my case at lease) https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Resources/doc/dealing_with_scopes.md
