### ISSUE TITLE
I have to reauthorize my application at every login. Am I doing something wrong?

### ISSUE THREAD

**Issue by naroga** [FriendsOfSymfony/FOSOAuthServerBundle#349]
In my LOGIN PROVIDER app, I'm using FOSAuthServerBundle + a custom user provider. In my LOGIN CONSUMER app, I'm using FOSUserBundle + HwiOathBundle to authenticate using the LOGIN PROVIDER app. Everything works fine, except that whenever I access `/connect/login-provider` in the LOGIN CONSUMER app, it **always** takes me to the authorization page (authorize.accept | authorize.reject buttons) on the LOGIN PROVIDER app. Even if the client/user combination had already been authorized.

When authenticating with facebook, it remembers which clients are authorized so I don't have to reauthorize them at every login request.

Did I do something wrong, or is it the default behaviour? How do I change this?

Thanks.

**Comment by Spomky** [comment]
See #167

**Comment by naroga** [comment]
Thank you @Spomky. If I understand it correctly, my application will need to deal with it manually (query to see if there is already an `AccessToken` for said user on said client) and manually `->setAuthorizedClient(true)` if so, right?

**Comment by Spomky** [comment]
That's it.
But do not forget that the main purpose of OAuth2 is ot introduce an authorization layer.
If you use `->setAuthorizedClient(true)`, the authorization page will always be bypassed. In this case OAuth2 is not the solution as it becomes useless.

**Comment by naroga** [comment]
I'll only `->setAuthorizationClient(true)` if a previous (and still valid) AccessToken for that user/client combination is already found (so the user won't need to reauthorize every time he logs in the same client).

Thank you.
