### ISSUE TITLE
Zlib_Decode error.

### ISSUE THREAD

**Issue by aylazhang** [FriendsOfSymfony/FOSOAuthServerBundle#353]
# composer require "friendsofsymfony/oauth-server-bundle:dev-master"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

**Comment by Spomky** [comment]
I do not think this issue is related to this bundle. 
Try to clear the cache of composer.

**Comment by stof** [comment]
This is an issue when running composer, not when running the bundle.
