### ISSUE TITLE
Unrecognized option "csrf_provider" under "security.firewalls.oauth_authorize.form_login"

### ISSUE THREAD

**Issue by gencer** [FriendsOfSymfony/FOSOAuthServerBundle#378]
Unrecognized option "csrf_provider" under "security.firewalls.oauth_authorize.form_login"

I get this error on 1.5.0-BETA with Symfony3. Any idea?

Note: CSRF is enabled under framework.

**Comment by gencer** [comment]
Maybe csrf_token_generator instead of current one?

**Comment by j0k3r** [comment]
I guess this is more a project configuration than related to this bundle.
https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/search?q=csrf_provider&type=Code&utf8=%E2%9C%93

**Comment by gencer** [comment]
@j0k3r indeed it is. There is nothing wrong with the bundle.

**Comment by Ener-Getick** [comment]
I close this issue then

**Comment by summermick** [comment]
I also got this issue when installing with api-platform, am using 
` "php": ">=7.0",
        "symfony/symfony": "3.2.*",
        "api-platform/core": "^2.0",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^3.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "dunglas/action-bundle": "^0.3",
        "nelmio/cors-bundle": "^1.4",
        "phpdocumentor/reflection-docblock": "^3.0",
        "friendsofsymfony/user-bundle": "~1.3"`
