### ISSUE TITLE
Overwriting Authenticate Manager

### ISSUE THREAD

**Issue by iBasit** [FriendsOfSymfony/FOSOAuthServerBundle#385]
Is it possible to overwrite authentication manager or OAuthProvider.

I want to check session value, rather then token. (but depending on token value)

```$token == 'session'```, then check session user.

**Comment by Ener-Getick** [comment]
You can probably simply overwrite the corresponding service (``fos_oauth_server.security.authentication.provider``)

**Comment by iBasit** [comment]
Thanks, I managed to do it, before for some reason it wasn't doing it.
