### ISSUE TITLE
Compatibility with Symfony

### ISSUE THREAD

**Issue by edamov** [FriendsOfSymfony/FOSOAuthServerBundle#387]
For example, I'm using Symfony 2.7.9. What version of bundle should I use?
I think the documentation is outdated in this question.

**Comment by Ener-Getick** [comment]
Just run ``composer require friendsofsymfony/oauth-server`` and it will do the job for you.

**Comment by codbox** [comment]
it's compatble with symfony >= 2.1| ~3.0

**Comment by Ener-Getick** [comment]
Yeah, what's the problem?

**Comment by Ener-Getick** [comment]
IMO we should just remove this part of the doc as sf <2.3 is not supported anymore.

**Comment by Ener-Getick** [comment]
Yeah, what's the problem?

**Comment by edamov** [comment]
@Ener-Getick Thanks!

**Comment by edamov** [comment]
@codbox What's mean vertical symbol "|" in this version ">= 2.1| ~3.0" ?

**Comment by Ener-Getick** [comment]
That means ``or`` so we support symfony 2.1 (included)  until symfony 4.0 (excluded). And this isn't the right version constraint, it's ``~2.1|~3.0`` which is strongly different.
