### ISSUE TITLE
utf8 not supported (MySQL Error 1071)

### ISSUE THREAD

**Issue by mikewop** [FriendsOfSymfony/FOSOAuthServerBundle#389]
This is similar to issue #368, but it applies to 3 tables not just AccessToken.
This seems to be an issue since 1.4.0. when a unique index was added to AccessToken, RefreshToken and AuthCode.

On MySQL the "token" column of these 3 tables is created as VARCHAR(255).

When doctrine tries to apply the indices, it will fail with Error 1071:
**"Error Code: 1071. Specified key was too long; max key length is 767 bytes"**

This is the SQL it is trying to apply:
CREATE UNIQUE INDEX UNIQ_6F5229945F37A13B ON Access_Token (token);
CREATE UNIQUE INDEX UNIQ_7BF0FDB15F37A13B ON Auth_Code (token);
CREATE UNIQUE INDEX UNIQ_B5F045645F37A13B ON Refresh_Token (token);

 If the tables/DB uses utf8_unicode_ci or any other multi-byte character set where a char can be 3 or more bytes, this error will happen (e.g utf8, utf8mb4).

Does the "token" column have to be 255 chars long or can it be shortened?

**Comment by Ener-Getick** [comment]
You have to override [``OAuth2::genAccessToken()``](https://github.com/FriendsOfSymfony/oauth2-php/blob/master/lib/OAuth2.php#L1406-L1424) and update the parameter ``fos_oauth_server.server.class`` to your own class name.
