### ISSUE TITLE
client_id format

### ISSUE THREAD

**Issue by NathanVss** [FriendsOfSymfony/FOSOAuthServerBundle#408]
In fact it is not really a issue, but a question.

Why did you choose to format client_id this way : id_(random_id). Why include the database id ?
It makes things harder for functionnal tests because the id can be incremented for any reason.

Thanks ;)

**Comment by Spomky** [comment]
See #328

**Comment by NathanVss** [comment]
Oh, I'm sorry I didn't found this one.
So, no news about this I guess ?

**Comment by Spomky** [comment]
There no news about this topic.
This [PR](https://github.com/Sylius/Sylius/pull/2887/files) fixes this issue by overriding the `getPublicId` method.
I think this is the best way to get rid of thqt issue.

**Comment by NathanVss** [comment]
Ok, thank you for your quick responses. 
Have a good day !
