### ISSUE TITLE
Custom header for access token

### ISSUE THREAD

**Issue by bakicdj** [FriendsOfSymfony/FOSOAuthServerBundle#421]
Is there any way of setting the access token in some custom header like X-Auth-Token, or something like that. I'm asking this because in my company we have a policy that all sites in the development phase should be protected with basic http auth. The problem is when basic auth is enabled, it sets the authorization header for every request and by doing that, users are not able to login via oauth. I tried to put access token in url, just for the current stage of the project, but oauth bundle seems to always check that header first, and everything fails. I have few dirty hacks on mind, but I would try to avoid them if I can. Any suggestion on this?

**Comment by Spomky** [comment]
The access token can also be passed in the query string.

If you really want a custom header, then it could be possible by overriding the method `getBearerTokenFromHeaders` of the class `OAuth2\OAuth2` ([see these lines](https://github.com/FriendsOfSymfony/oauth2-php/blob/master/lib/OAuth2.php#L594-L633))

**Comment by bakicdj** [comment]
I override the method from above. 
Thank you :)

I know this would be against the protocol, but wouldn't be good if you could set the header name in config?
