### ISSUE TITLE
Impossible to disable authorize

### ISSUE THREAD

**Issue by vincentchalamon** [FriendsOfSymfony/FOSOAuthServerBundle#465]
According to [configuration](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/DependencyInjection/Configuration.php#L65), it should be possible to disable `authorize` key. But if I do, I get the following error:
> You have requested a non-existent service "fos_oauth_server.authorize.form"

I'm trying to migrate to Symfony 3.3, which disables forms by default, and I don't want forms & authorize neither (it's a private API).

**Comment by TNAJanssen** [comment]
https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/462

**Comment by florianajir** [comment]
can this is be fixed ? I don't want to require dependencies that I don't use... (twig, templating, etc.)

**Comment by elvismdev** [comment]
Trying to install the bundle in SF4 but got this error, I think it's related. Prefer to not install extra packages I don't need like twig.

```
The service "fos_oauth_server.authorize.form" has a dependency on a non-existent service "form.factory".
```

**Comment by vincentchalamon** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/554
