### ISSUE TITLE
Using FOSOAuthServerBundle without FOSUserBundle

### ISSUE THREAD

**Issue by Linkinou** [FriendsOfSymfony/FOSOAuthServerBundle#467]
Hello ! 

I need some information about how to use FOSOAuthServerBundle without FOSUserBundle.

As I understand I need a custom UserProvider (which I've created using http://symfony.com/doc/current/security/custom_provider.html) and I also need something to authenticate the user. I wanted to build my own authenticator using GuardAuthenticatorInterface.

But I don't know how to fit my custom authenticator in FOSOAuthServerBundle process.

Currently, when I hit the /token endpoint with my client_id, client_secret, username and password, my API give me an access_token but no user was bind to it.

Moreover I don't understand if I need login_form in security.yml since I do not use a login form... :/  

Any advices/suggestions would be fantastic :)  

Thank you

**Comment by alexbonhomme** [comment]
Hey @Linkinou !

I was facing the same problem today. So basically you have to : 

1. Create a service class who implements `UserProviderInterface` (gonna have to implements `loadUserByUsername(), refreshUser() and supportsClass()`
2. Configure your service in `services.yml`
3. Configure `user_provider` of oauth in `config.yml` with the name you gave to your service in `services.yml`
4. Eventually configure the `providers` section with your user model class (I don't really understand this part, I may be wrong and this could by useless). eg : 
```
user_provider:
        entity: { class: AppBundle\Entity\User, property: email }
```

And you should be ok !
Alex

**Comment by dinamic** [comment]
@Linkinou, if you have found a solution, please feel free to close the issue.

**Comment by conceptdeluxe** [comment]
I wasted a lot of time assuming that I can configure the provider below `providers:` key in `security.yaml`, but in fact there is no need to add the provider there at all - it has nothing to do with it. Instead I have my config like this now:

```
fos_oauth_server:
    ...
    service:
        user_provider: App\MyOAuthUserProvider
```
```
services:
    ...
    App\MyOAuthUserProvider:
        arguments: ['@doctrine.orm.entity_manager']
```
