### ISSUE TITLE
Is this bundle still maintained ?

### ISSUE THREAD

**Issue by Prometee** [FriendsOfSymfony/FOSOAuthServerBundle#488]
Since one year no commits nor accepted PR, is this bundle still maintained ?

Is there an other bundle that already make the same job ? (one compatible with symfony 4 ?)

**Comment by dkarlovi** [comment]
Hi, I've been added as a contributor a short while ago because I had similar concerns. As it stands, I plan to start development on it shortly, in the meantime review and merge PRs, do releases.

**Comment by j-datadome** [comment]
Hi @dkarlovi 

This bundle is very nice and we need it to be compatible with SF4 (as other people who wants to migrate from SF3 to SF4 I guess)
Of course I follow this related PR: https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/485

Do you know when it would be possible to do it?
Like @Prometee I'm starting to look for an alternative because this feature is a requirement for us to migrate Symfony

Thx a lot

**Comment by dkarlovi** [comment]
Hi @j-datadome,

I'd like to see #485 merged ASAP, but currently it contains a BC break which needs to be addressed there. I'm currently switching from full time employment to being a freelance developer / consultant, which should leave me with more time doing OSS, hopefully. :)

**Comment by j-datadome** [comment]
Hi @dkarlovi,

Thank you for replying!
Yes, I read the PR and the discuss into and I understand you'd like to fix it of course.
My concern is the delay to get it available as we need to switch to SF4 very, very soon. To be honest, this bundle is the only one which blocks the migration, but it is absolutely required, and, if possible, I'd like to keep it as it is very nice :-)

Well, hope you could manage this ASAP
Regards

**Comment by Prometee** [comment]
For me is also FOSUser that stop us from upgrading to sf4, but to wait, we update our projets to sf3.4 structure and configs so FOSRestBundle already work with 3.4, it need some manual configs before requiring the bundle but it work.

**Comment by mvrhov** [comment]
I just went through something similar and there are 3 very popular oauth2 server implementations. This one, the one form [league](https://packagist.org/packages/league/oauth2-server) and [bshaffer](https://github.com/bshaffer/oauth2-server-bundle). 
The league one doesn't have the bundle.
The bshaffer one also supports implict grant and a jwt one if one needs it.

**Comment by j-datadome** [comment]
@mvrhov thank you for the info
we gonna consider move to one of these implementations if it takes too much time to get the FOSOAuthServerBundle available

**Comment by Sohorev** [comment]
Very need for SF4 support

**Comment by SebScoFr** [comment]
Really keen to see that SF4 support come to light as well. That's a bit of a blocker for us too. :)

**Comment by dkarlovi** [comment]
SF4 support (and fixing SF3 support too) will be added ASAP, which means releasing 1.6 then.

**Comment by francoispluchino** [comment]
@dkarlovi It is not rather for the version 2.0?

**Comment by dkarlovi** [comment]
@francoispluchino sorry, don't quite understand, can you elaborate?

**Comment by francoispluchino** [comment]
I was thinking that you remove the support for the Symfony 2.x, but it is not the case. So the my question is useless. On the other hand, the 1.6 version does not exist, but there are 2 dev branches: 1.5.x-dev and 2.0.x-dev. Maybe create a new 1.6 branch?

**Comment by dkarlovi** [comment]
Yes :see_no_evil:  I've PEBKACed and created a 1.5 branch instead of 1.6, will rename it. Think of 1.5 as 1.6, 2.0 will drop Symfony 2.x support.

**Comment by cored0wn** [comment]
Is branch 1.6 stable ? If so can you tag them so I can add it to my composer.json?

**Comment by dkarlovi** [comment]
It should be stable and support Symfony 2.x, 3.x, 4.x (which is insane, that's why 2.x is dropping Symfony 2.x support). We still have some issues open which should be resolved before tagging.

**Comment by zablik** [comment]
@dkarlovi Thanks a lot for the support! 
Can it be approximately estimated when the new stable version will be tagged? We've just started development and we need to make a decision on the version to use.
Thanks!

**Comment by danielkeho11** [comment]
> I just went through something similar and there are 3 very popular oauth2 server implementations. This one, the one form [league](https://packagist.org/packages/league/oauth2-server) and [bshaffer](https://github.com/bshaffer/oauth2-server-bundle).
> The league one doesn't have the bundle.
> The bshaffer one also supports implict grant and a jwt one if one needs it.

The league one have a [bundle](https://github.com/trikoder/oauth2-bundle) now.

**Comment by danielkeho11** [comment]
> I just went through something similar and there are 3 very popular oauth2 server implementations. This one, the one form [league](https://packagist.org/packages/league/oauth2-server) and [bshaffer](https://github.com/bshaffer/oauth2-server-bundle).
> The league one doesn't have the bundle.
> The bshaffer one also supports implict grant and a jwt one if one needs it.

The league one has a [bundle](https://github.com/trikoder/oauth2-bundle) now.
