### ISSUE TITLE
Deprecate Symfony\Component\Security\Core\SecurityContextInterface in FOS\OAuthServerBundle\Security\Firewall\OAuthListener

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSOAuthServerBundle#500]
In 1.5 branch, interface was removed from Symfony v3, 2.x will not support Symfony v2.

**Comment by dinamic** [comment]
Is this to be resolved in 2.x or in 1.6? It is tagged as in the milestone 1.6, but the description says 2.x. Which is true?

**Comment by dkarlovi** [comment]
Resolved in 1.6, removed in 2.0 Done in #506
