### ISSUE TITLE
Symfony 3.x compatibility

### ISSUE THREAD

**Issue by dinamic** [FriendsOfSymfony/FOSOAuthServerBundle#505]
Hello guys,

I have found multiple places that need changing in order to have Symfony 3.x compatibility.

One of the things to improve is removing the usage of `SecurityContext` and `SecurityContextInterface`. Issues are already posted for this. Examples are the `SecurityController` as well as #500.

We could possibly tag the problems with label `SF3` and submit PRs that can go to a new tag - let's say `1.6`.

**Comment by dinamic** [comment]
It may be a good idea to have the composer.json updated, so people won't feel frustrated as I did when things were not working the way they should be.

It's better to have an error message saying the bundle is not compatible than have it half-working without any error messages and no clue on what is wrong.

**Comment by dkarlovi** [comment]
That's the point, currently the bundle is supposed to be compatible with Symfony v2 and v3, but it seems it isn't really. We should add more tests to confirm v4 compatibility which is being worked on in #503

**Comment by dinamic** [comment]
Sounds reasonable. If there is a roadmap and people get assigned to different tasks, I may try to spare some time and help you guys out. :)

**Comment by dkarlovi** [comment]
I don't find getting assigned a task is really any more productive than the usual "found a problem, fixing it" approach each individual takes if interested. :)

You definitely found a problem here, a PR adding tests to confirm Symfony integration would be great. :+1:

**Comment by dkarlovi** [comment]
@dinamic is this closed with #512?

**Comment by dinamic** [comment]
@dkarlovi, I have to review the changes, but I won't be able to spend time on it before Thursday.

**Comment by dinamic** [comment]
@dkarlovi I think we can close this one down. If there are any issues, they have to be submitted on per-case basis.

I have 1.5 branch running on Symfony 3.3 and I haven't experienced any issues.
