### ISSUE TITLE
  The definition for "fos\oauthserverbundle\controller\tokencontroller" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.  

### ISSUE THREAD

**Issue by devRoshan** [FriendsOfSymfony/FOSOAuthServerBundle#509]
Can anyone help me to get rid of this error ? my symfony app version is 2.8 .

**Comment by mikrafizik** [comment]
Same issue app version 2.8.17

**Comment by mikrafizik** [comment]
@devRoshan , update your composer json dependency to 

> "friendsofsymfony/oauth-server-bundle": "1.5.0",

and run composer update, it works for me

**Comment by dinamic** [comment]
@devRoshan, have you managed to get this resolved?

You should be using FOSOAuthServerBundle 1.5.*. Could you confirm this?

**Comment by devRoshan** [comment]
@dinamic its working now, thank you

**Comment by dinamic** [comment]
Happy to help, @devRoshan.

Could you please close this issue down? :)

**Comment by jakesyl** [comment]
Thanks! this worked great.

**Comment by TPete** [comment]
I'm seeing this error again after upgrading to 1.6.0.

**Comment by dkarlovi** [comment]
Yes, this was not actually solved, OP only downgraded to 1.5.

**Comment by FlorianKoerner** [comment]
Same issue here . 😢

**Comment by dkarlovi** [comment]
You can downgrade back to 1.5.2 until this is resolved, we'll push a bugfix for this ASAP.

**Comment by nclavaud** [comment]
Looks related to commit https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/503/commits/36e552af620b8815f63a008b0ce4af8423943bcf in pull https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/503

Looks like Symfony 2.8 does not handle the new syntax introduced in 3.4 where services can be defined without a `class` property when their ID is a FQCN.

I can't understand why an alias has been introduced instead of making the service explicitely public, though :thinking:

**Comment by dkarlovi** [comment]
> Looks like Symfony 2.8 does not handle the new syntax introduced in 3.4 where services can be defined without a class property when their ID is a FQCN.

We should really introduce actual functional tests to catch these sorts of errors ASAP. :(

> I can't understand why an alias has been introduced instead of making the service explicitely public, though

Services in Symfony became private by default, by which this bundle's services became private too. Having services be public should be a rare exception, not the norm.

**Comment by nclavaud** [comment]
Looks like https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/551 is attempting to fix this very same issue

**Comment by dkarlovi** [comment]
Can anybody confirm 1.6@dev works on Symfony 2.x?

**Comment by nclavaud** [comment]
> Can anybody confirm 1.6@dev works on Symfony 2.x?

I do. All fine with https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/commit/5cc4c8555dedb5c7e737a35789bd429ccd9ad254 (1.6@dev) on top of Symfony 2.8.38, whereas we had the error reported above with https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/commit/98a66424c33ea1ad4773644dae3597725410f762 (1.6.0) when running `composer install`.

So :+1:

**Comment by dkarlovi** [comment]
1.6.1 has been released, please update and confirm this works now.
