### ISSUE TITLE
Can't create clients on Windows, uniqueid error

### ISSUE THREAD

**Issue by novacp** [FriendsOfSymfony/FOSOAuthServerBundle#515]
When trying to create a client on Windows (command or programatically), uniqueid() for generating a randomToken within FOS\OAuthServerBundle\Util\Random returns an error: 

"Type error: uniqid() expects parameter 1 to be string, integer given in C:\xampp\htdocs\ms-bp-sf4\vendor\friendsofsymfony\oauth-server-bundle\Util\Random.php:31"

**Comment by dkarlovi** [comment]
Hello, thank you for reporting this.

Two things to note:

1. our test case should have caught that (/cc @dinamic WDYT?)
2. you shouldn't be using a branch in development (such as master), it will probably break on you a lot until we add more tests, use a released version

**Comment by dinamic** [comment]
@dkarlovi, we don't have a test coverage for this file.

**Comment by dinamic** [comment]
#518 should fix this.

**Comment by novacp** [comment]
Yes seems legit, but could you merge this please into version 1.6 too? Because I need sf4 and it seems as if 1.6@dev supports it.

Best regards and thanks for your fast response.
