### ISSUE TITLE
Tag 1.6.0 with oauth2-php ^1.1

### ISSUE THREAD

**Issue by dinamic** [FriendsOfSymfony/FOSOAuthServerBundle#538]
There are a few things here. The order is random, although tagging should be after the change with oauth-php version requirement.

1. Tag 1.6.0

We have 1.6 branch and the code inside should be stable. We should have a tag as well, so it could be installable without `-dev` suffix.

2. Raise `"friendsofsymfony/oauth2-php": "~1.1"` to allow 1.2.x, maybe `^1.1` would suffice.

We need to raise a bit the requirement for oauth-php, as currently it goes as `"friendsofsymfony/oauth2-php": "~1.1"`. While this works, issues like #528 can't be fixed as they require the most recently tagged version 1.2.3.

**Comment by dinamic** [comment]
PIng @dkarlovi

**Comment by dkarlovi** [comment]
We should raise reqs to 1.2.3+. I'd like to get [a couple of issues](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/milestone/2) finished before tagging.

**Comment by GuilhemN** [comment]
There is no need to bump `friendsofsymfony/oauth2-php` requirement, but we need to fix https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/528#issuecomment-365909311.

**Comment by francoispluchino** [comment]
@GuilhemN The issue #539 has been merged and should have fixed the mentioned problem. 

Currently, we are forced to use the `1.6-dev` development branch, because we don't have a tagged version.

@dkarlovi When do you expect to create the `v1.6.0` tag? Thank you for your great work!

**Comment by dkarlovi** [comment]
@francoispluchino sorry about the delay. We're down to a single thing in the 1.6 milestone, if you could send a PR, we can tag today. :+1:

**Comment by francoispluchino** [comment]
@dkarlovi See the PR #560.

**Comment by pamil** [comment]
I guess this issue can be closed as v1.6.0 with Symfony 4 support has been released, big thanks for that! 🎉

**Comment by francoispluchino** [comment]
@pamil Yes
