### ISSUE TITLE
When I make a refresh token, the user is deleted

### ISSUE THREAD

**Issue by zekjamel** [FriendsOfSymfony/FOSOAuthServerBundle#542]
Hi,
Everything is OK when I create an acces token with refresh token
Input :
`{
"grant_type" : "password",
"client_id" : $clientId,
"client_secret" : $secret,
"username" : "user@name.login",
"password" : "p@ssword"
}`

Output : 
`{
"access_token": "YmZmYjExMWYxYzc4YTBlZjVhZjEyZjU4YzI0YzlhODZmZDM3ZWIwMjY5MTNjZGIxNWQ2MTFjYjQyNDcxZDAwZQ",
"expires_in": 10800,
"token_type": "bearer",
"scope": null,
"refresh_token": "NTc0MWJhZDJlNzJiNGIwYjJlNjFkYWUyOTI3NjJhN2JkNWE0MGI1YTFiOGI1MDJiZDIyZGQ2MTM0YWM5MDE4Ng"
}`

Same thing when I use the refresh token :
Input :
`{
  "grant_type": "refresh_token",
  "client_id" : $clientId,
  "client_secret" : $secret,
  "refresh_token": "NTc0MWJhZDJlNzJiNGIwYjJlNjFkYWUyOTI3NjJhN2JkNWE0MGI1YTFiOGI1MDJiZDIyZGQ2MTM0YWM5MDE4Ng"
}`

Output :
`{
    "access_token": "NDdlZjczZjk4OGUwN2NjM2M3ZGExNzUyNDU0NzEyNzVjOTgwNTg3YzhlNTA2NmY3NmU0MjQxNzMxYjdkNmM3Ng",
    "expires_in": 10800,
    "token_type": "bearer",
    "scope": null,
    "refresh_token": "Y2Q2NDUwYjI3ZmY1NzlmNmQ1N2RlYWM0NWY4NjBkZmI4NjJlNjZkYmFjNmE3NjY0NTRlYTViYjk0NDIzN2Y4YQ"
}`

But after that, the user_id is deleted and all access_token and refresh_token with this user_id are deleted from  oauth2_access_token, oauth2_refresh_token and user's tables.

I do not understand why this... :-(

Thanks for any help

Jamel

**Comment by zekjamel** [comment]
Hi guys !

Any one has encountered this problem?

**Comment by zekjamel** [comment]
UP

**Comment by Baachi** [comment]
Hey @zekjamel this Bundle does not delete the user directly. It only deleted expired access token throw DQL, but this does not affect users. Do you checked your database constraints, for "onDelete" constraints or maybe cronjobs?

**Comment by zekjamel** [comment]
Hi they are "onDelete" constraints, thanx
