### ISSUE TITLE
Autowire EntityManager throws exception "Multiple services exist"

### ISSUE THREAD

**Issue by martinjandl** [FriendsOfSymfony/FOSOAuthServerBundle#556]
Hello,
when I autowire EntityManager an exception is thrown:

[Symfony\Component\DependencyInjection\Exception\RuntimeException]
Unable to autowire argument of type "Doctrine\ORM\EntityManager" for the service "autowired.AppBundle\Model\Shop\ShopRepository".
Multiple services exist for this class (doctrine.orm.default_entity_manager, fos_oauth_server.entity_manager).

Symfony 3.2.4

How to deal with that ?
Thank you.

**Comment by dkarlovi** [comment]
Autowire support is pending in #540

**Comment by dkarlovi** [comment]
Closed with #560

**Comment by zkday** [comment]
we meet the issue with Symfony 2.8. Any solution to support?

**Comment by er1z** [comment]
@zkday — I'm afraid unsupported version of Symfony will remain also unsupported here. The only thing I came across is to create own `CompilerPass` for this definition and bind everything manually. Don't remember if 2.8 also allows to bind a particular parameter as in newest editions but creating a compiler pass should give you a workaround.
