### ISSUE TITLE
Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by kvnbai** [FriendsOfSymfony/FOSOAuthServerBundle#565]
Symfony version: 4
PHP version 7.2

Symfony\Component\HttpFoundation\Response's status needs an integer yet FOS\OAuthServerBundle\Security\EntryPoint\OAuthEntryPoint gives a string ('401 Unauthorized' by OAuth2\OAuth2::HTTP_UNAUTHORIZED)

**Comment by fxbt** [comment]
This was fixed by #539 in the 1.6.

It should be available soon.
