### ISSUE TITLE
Bundle fails on Symfony4

### ISSUE THREAD

**Issue by er1z** [FriendsOfSymfony/FOSOAuthServerBundle#579]
```
The option "validation_groups" does not exist. Defined options are: "action", "attr", "auto_initialize", "block_name", "by_reference", "compound", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "inherit_data", "label", "label_attr", "label_format", "mapped", "method", "post_max_size_message", "property_path", "required", "translation_domain", "trim", "upload_max_size_message".
```

After commenting out ``Resources/config/authorize.xml:13``:
```
                <argument key="validation_groups">%fos_oauth_server.authorize.form.validation_groups%</argument>
```

Everything seems to work ok. Are the validation groups used within something needed?

**Comment by leroy0211** [comment]
Doesn't break on my end. But I'm using the traditional symfony 4.0. Not the flex version.

**Comment by stof** [comment]
@er1z could you be using the Form component without the Validator component ?

**Comment by stof** [comment]
maybe we are missing some requirements in this bundle (it has been written long before the Flex area, where everyone was installing the fullstack repo)

**Comment by er1z** [comment]
@stof executing ``composer require validation`` fixed the problem, thanks.
