### ISSUE TITLE
Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid()

### ISSUE THREAD

**Issue by scootstah** [FriendsOfSymfony/FOSOAuthServerBundle#581]
**Symfony FOSOAuthServerBundle versions**:
friendsofsymfony/oauth-server-bundle 1.6.1

**Description of the problem including expected versus actual behavior**:
A `LogicException` is thrown for POST requests to /oauth/v2/auth, with the message:
`Cannot check if an unsubmitted form is valid. Call Form::isSubmitted() before Form::isValid()`

**Steps to reproduce**:
 1. Submit POST request to /oauth/v2/auth

**Provide logs (if relevant)**:

**Comment by mykiwi** [comment]
Any news on when the fix will be merged (or why it's not merged & released yet) ?

**Comment by mykiwi** [comment]
ping @arnaud-lb @dkarlovi @GuilhemN

**Comment by puterakahfi** [comment]
Hi all, any update about this issue?
I face the same problem 

Thanks

**Comment by DiegoJohan** [comment]
Hi everyone, some solution for this issue? I have the same problem

**Comment by GuilhemN** [comment]
Fix merged and released https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/releases/tag/1.6.2
