### ISSUE TITLE
Symfony 4.1 configuration problems

### ISSUE THREAD

**Issue by brutalnv** [FriendsOfSymfony/FOSOAuthServerBundle#588]
I got an error after adding

#app/config/routing.yml
fos_oauth_server_token:
resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

> There is no extension able to load the configuration for "fos_oauth_server_
  !!    token" (in /var/app/ondeck/config/packages/routing.yaml). Looked for namesp
  !!    ace "fos_oauth_server_token", found "framework", "twig", "security", "nelmi
  !!    o_cors", "doctrine_cache", "doctrine", "api_platform", "fos_oauth_server" i
  !!    n /var/app/ondeck/config/packages/routing.yaml (which is loaded in resource
  !!     "/var/app/ondeck/config/packages/routing.yaml").

**Comment by brutalnv** [comment]
Solved. I made a mistake during the configuration process.

**Comment by AbdallahOuahib** [comment]
What is the mistake, it can help others
