### ISSUE TITLE
Remove dependency on random_compat < 1.x

### ISSUE THREAD

**Issue by Trekels** [FriendsOfSymfony/FOSOAuthServerBundle#597]
The dependency on `random_compat` was introduced in version 1.6 [see here](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/518), but it allows the installation of versions lower then 2.x

This introduces a vulnerability issue referenced here [here](https://github.com/paragonie/random_compat/issues/96)

Requested is to to remove the `^1` reference.

**Comment by alister** [comment]
This can also be updated to include '^2|^9.99'. The v9.99 is a no-op version of the library as the functions are already provided on PHP7. See https://github.com/paragonie/random_compat#version-99999
