### ISSUE TITLE
Symfony 4.3 triggers deprecation errors because of dependency on templating

### ISSUE THREAD

**Issue by potasiyam** [FriendsOfSymfony/FOSOAuthServerBundle#616]
Symfony 4.3 has deprecated templating component integration and will be removed in Symfony 5. 
https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration
Right now it triggers deprecation errors when running tests. Is there any plan in near future on new implementation without the dependency on templating?

**Comment by hhamon** [comment]
Hello!

What's the status of this issue?

**Comment by jimb00b** [comment]
Hello, any news here?

**Comment by deguif** [comment]
Closing as it was done in #653
