### ISSUE TITLE
The spaceless tag in FOSOAuthServerBundle::form.html.twig at line 3 is deprecated since Twig 2.7, use the spaceless filter instead

### ISSUE THREAD

**Issue by crmpicco** [FriendsOfSymfony/FOSOAuthServerBundle#618]
On the latest version of the bundle there are deprecation messages appearing around deprecated Twig functions.

> User Deprecated: The spaceless tag in FOSOAuthServerBundle::form.html.twig at line 3 is deprecated since Twig 2.7, use the spaceless filter instead.

Are there fixes for these available or would you consider a pull request?

**Comment by alcaeus** [comment]
Closing in favour of #616.
