### ISSUE TITLE
OpenId Provider

### ISSUE THREAD

**Issue by abdul-jabbar01** [FriendsOfSymfony/FOSOAuthServerBundle#626]
I'm still curious for any documentation or any answer that whether this bundle supports **OpenID** and is there any implementation to **use this bundle as an** **OpenId provider**? 

Any answers will be highly appreciated

**Comment by stof** [comment]
OpenId is not implemented in this bundle.

**Comment by abdul-jabbar01** [comment]
Is there any type of documentation or some stuff which explains how to upgrade this package for OpenID Provider?

**Comment by stof** [comment]
No such documentation. And I don't know which kind of work would be needed (I'm not using that bundle).

**Comment by abdul-jabbar01** [comment]
Okay. Thanks for your response.
