### ISSUE TITLE
Security fix for FriendsOfSymfony/oauth2-php

### ISSUE THREAD

**Issue by DeChaun** [FriendsOfSymfony/FOSOAuthServerBundle#641]
Hi there

FriendsOfSymfony/oauth2-php has released a minor update to fix a [security issue](https://github.com/FriendsOfSymfony/oauth2-php/pull/121).

Am I right to suggest this bundle should update its composer requirements for the oauth2-php bundle to version 1.3.0?

Thanks in advance!

**Comment by fliespl** [comment]
@DeChaun From what I see - it's not really a security fix, but simply a bug fix.

It failed to allow redirectUri under certain scenario, but it should (not the other way around - that's why it's not security fix).

**Comment by deguif** [comment]
Let's close now it was released
