### ISSUE TITLE
Get the current OAuth client

### ISSUE THREAD

**Issue by pierrre** [FriendsOfSymfony/FOSOAuthServerBundle#81]
Is it possible to get the current oauth client?
I can't find a way to do it properly.

Here is my idea:
- Add a `client` field in [FOS\OAuthServerBundle\Security\Authentication\Token\OAuthToken](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Security/Authentication/Token/OAuthToken.php)
- Edit [FOS\OAuthServerBundle\Security\Authentication\Provider\OAuthProvider](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Security/Authentication/Provider/OAuthProvider.php) and set the `client` in `OAuthToken`

Is it ok?

**Comment by AlmogBaku** [comment]
I agree, storing this info on the token entity sounds more efficient.
cc: @willdurand what do you think?

**Comment by AlmogBaku** [comment]
Why doesn't https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/tree/feature/client-on-token merged to the master?

**Comment by dkarlovi** [comment]
There's a branch in the bundle, there's #188, why hasn't this been merged yet?

**Comment by GuilhemN** [comment]
Sorry I don't have the time to review this bundle's PRs anymore... But I can add you as collaborator if you're willing to maintain this bundle.

**Comment by dkarlovi** [comment]
I'll do my best, let's do it. 👍

**Comment by GuilhemN** [comment]
Done :)

**Comment by dkarlovi** [comment]
Thinking about this, we shouldn't set the client, instead we should inject the whole token instead of only the string. Will work on this for 2.0.
